#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>
#include <furi_hal.h>
#include <stdlib.h> // Pro generování náhodných hodnot

/* generated by fbt from .png files in images folder */
#include <uv_sensor_icons.h>

// Struktura pro data aplikace
typedef struct {
    Gui* gui;
    ViewPort* view_port;
    bool running;
    float uva, uvb, uvc; // UV hodnoty
} UVSensorApp;

// Funkce pro simulaci skenování (náhodné hodnoty)
static void uv_sensor_scan(UVSensorApp* app) {
    // Zapne LED (Flipper používá power LED, ne GPIO)
    furi_hal_power_led_test(true);

    // Generování náhodných UV hodnot
    app->uva = (float)(rand() % 500) / 100.0; // 0.00 - 5.00
    app->uvb = (float)(rand() % 500) / 100.0; // 0.00 - 5.00
    app->uvc = (float)(rand() % 500) / 100.0; // 0.00 - 5.00

    // Pípnutí jako indikace skenu
    furi_hal_speaker_start(1000, 100);
    furi_delay_ms(100);
    furi_hal_speaker_stop();

    // Vypne LED
    furi_hal_power_led_test(false);
}

// Funkce pro vykreslení obrazovky
static void uv_sensor_render(Canvas* canvas, void* ctx) {
    UVSensorApp* app = ctx;

    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);

    canvas_draw_str(canvas, 10, 10, "UV Sensor");

    char buffer[32];

    snprintf(buffer, sizeof(buffer), "UVA: %.2f", (double)app->uva);
    canvas_draw_str(canvas, 10, 25, buffer);

    snprintf(buffer, sizeof(buffer), "UVB: %.2f", (double)app->uvb);
    canvas_draw_str(canvas, 10, 40, buffer);

    snprintf(buffer, sizeof(buffer), "UVC: %.2f", (double)app->uvc);
    canvas_draw_str(canvas, 10, 55, buffer);
}

// Funkce pro ovládání tlačítek
static void uv_sensor_input(InputEvent* event, void* ctx) {
    UVSensorApp* app = ctx;

    if(event->type == InputTypeShort) {
        if(event->key == InputKeyBack) {
            app->running = false; // Ukončení aplikace
        } else if(event->key == InputKeyOk) {
            uv_sensor_scan(app); // Spustí nový scan
            view_port_update(app->view_port); // Aktualizace obrazovky
        }
    }
}

// Hlavní funkce aplikace
int32_t uv_sensor_app(void* p) {
    UNUSED(p);

    UVSensorApp app;
    app.gui = furi_record_open(RECORD_GUI);
    app.view_port = view_port_alloc();
    app.running = true;

    // Výchozí UV hodnoty
    app.uva = 2.5;
    app.uvb = 1.8;
    app.uvc = 0.4;

    view_port_draw_callback_set(app.view_port, uv_sensor_render, &app);
    view_port_input_callback_set(app.view_port, uv_sensor_input, &app);
    gui_add_view_port(app.gui, app.view_port, GuiLayerFullscreen);

    // Hlavní smyčka aplikace
    while(app.running) {
        furi_delay_ms(100);
    }

    // Uklid a ukončení aplikace
    gui_remove_view_port(app.gui, app.view_port);
    view_port_free(app.view_port);
    furi_record_close(RECORD_GUI);

    return 0;
}
